### ISSUE TITLE
Untrustworthy results. Is this still maintained?

### ISSUE THREAD

**Issue by michaelkoelewijn** [franciskim/check-mixed-content#4]
Thanks for your plugin.
However it is flawed.

```
let bad = false
let active = false
let $ = cheerio.load(data.body)
$('img').each(function () {
    if ($(this).attr('src')) bad = $(this).attr('src').indexOf('http:') > -1
    if ($(this).attr('srcset')) bad = $(this).attr('srcset').indexOf('http:') > -1
})
```

Imagine if there are 2 images on a page where the first triggers the variable `bad` to be set to true.
If the next image on the page is valid the variable `bad` will become false again.
This will not result in a mixed content warning while it should.

In my own project i have fixed this. Let me know if this repo is still maintained so i can send you a PR.

**Comment by franciskim** [comment]
@michaelkoelewijn no it's not maintained and yes it seems the logic is flawed. It was very quickly done as an MVP. Happy to merge in your PR.

**Comment by franciskim** [comment]
Merged
